apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tvyuqjg3k-go 
  janus-idp.io/tekton: tvyuqjg3k-go
  backstage.io/kubernetes-id: tvyuqjg3k-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tvyuqjg3k-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml